### ISSUE TITLE
Suggest reword explaining initial increase in Rt.

### ISSUE THREAD

**Issue by seabbs** [BDI-pathogens/LocalCovidTracker#4]
The explanation as given is (see screenshot): "The apparent increasing R through the first half of March is likely an artefact of our method: we are not aware of any reasons to suppose that R was actually increasing during this time."

![Screenshot 2021-02-10 at 16 43 34](https://user-images.githubusercontent.com/20317649/107541522-1fb7d900-6bbf-11eb-9e16-0ffd74e97313.png)

I'd suggest a reword to clarify exactly what is happening here or restrict the plots as this period of time will be spurious and could potentially lead to bias if not truncated by downstream users. Interestingly most implementations of `EpiEstim` are biased upwards in the first few days due to no past case data to calculate infectiousness. This could potentially be linked to #3.

**Comment by MichelleKendall** [comment]
Ok. We discussed this at length as a team and decided not to restrict the plots or truncate because it is not clear when to do so: waiting until all areas have finished their increasing phase would remove a substantial period where other estimates are informative (though of course we are still to address your queries about the backcalculation) and starting a line at its individual peak R(t) could appear to attribute unwarranted confidence in that estimate at a time when the confidence intervals are very wide (see plot below, and also included in the .csv file for downstream users).

**Comment by seabbs** [comment]
Great! Given that I still think a more nuanced discussion (i.e what artefact) than given would be helpful. 

On the evidence for truncation given that `EpiEstim` uses the renewal equation estimates produced up to at least the mean of the generation time has passed are going to be pretty flawed regardless of what you do. If you are looking to reword one additional issue may be imported cases.
