### ISSUE TITLE
Nowcast interpretation

### ISSUE THREAD

**Issue by seabbs** [BDI-pathogens/LocalCovidTracker#6]
I am quite confused about your nowcast implementation. Usually this is used when cases have been adjusted from date of report to date of infection and then upscaled to account for right truncation if needed. In addition, when used for a complete time series it usually means that cases by date of infection have been  scaled to get true infections using some measure of underreporting etc. In your back casting approach that would mean that you only need to nowcast the last several weeks of data. 

What I see in your code and detailed in the SI of the linked methods is that the nowcast is instead Rt * weekly average of cases by infection. Based on that, should it be interpreted as cases that will be infected in the next few weeks from infections now? This interpretation makes me quite confused about the time indexing as I would have thought you would want to use the generation time to convolve projected cases to their own date of infection (rather than their infectees date of infection) or use the renewal equation with a projection of Rt.

If keeping as is (so indexed by date of infection of infectee), it might be helpful to clarify this. 

I am sure I am getting the wrong end of the stick here but perhaps it could do with clarification in your app (I checked this using Norfolk as an example with an Rt of 1.4 on the 22nd of December, cases by date of infection of 70 and nowcast of 93 (giving 98 = 1.4 * 70)).

Implementation: https://github.com/BDI-pathogens/LocalCovidTracker/blob/f0296510d2f95a16a3e6a1fb4cae780c20dfd084/prep/daily_tracker_scraper.R#L150

**Comment by MichelleKendall** [comment]
Let me see if I can clarify:
* yes exactly: the nowcast N(t) = R(t) * mean(new infections during week t-3 to t+3)
* I think the best interpretation is as given on the y-axis: it's the expected number of infections which will go on to be confirmed by a positive test result per day in the near future, per 100,000 population. That is, no upscaling (just infections who go on to be cases) and "near future" meaning just one generation time from each of the new infections that started in that week. The right truncation is handled within our estimates of R, for which we censor the last 12 days of estimates.
* the nowcast inherently assumes no interventions, i.e. it should be thought of as "if next week continues like this week, how many _infections which will go on to be cases_ should we expect per day?" However, it was never intended as a predictive tool, merely as a means of combining the R rate and the infection rate to give a more informative comparison between areas than from using either measure alone. It should be thought of more as an assessment of the epidemic in one area relative to the others.
* your example helped me spot a little error in my code so thanks for drawing my attention for that: I was accidentally using the week (t-2 to t+4) for infections within in the nowcast calculation. But yes: on 22nd December Norfolk had an estimated 68.7 new infections (per 100,000 population - forgive me if I don't keep writing that). The average for that week (19th - 25th) is ~65. R(t) is just over 1.4. So N(t) is 91.7. But of course Norfolk didn't reach 91.6 new infections per day (thankfully) because that estimate occurred at a peak in R(t). Perhaps more informative for understanding the intuition here is to look at a time when the number of new infections was rising more regularly, e.g. 6th December. R(t) was 1.4 and the number of new infections per day was 23.9. The nowcast tells us to expect 35.2 cases per day in the near future, and we reach that on 11/12th December. But again, it's not meant to be a predictive tool, just a means of comparing areas. Loosely speaking, when we look back we can see that if an area did follow its nowcast trajectory then there wasn't much change in interventions / behaviours etc., and if it didn't then there was. Which is our reason for keeping historic estimates available rather than just a very recent picture. 

Hope that helps?

**Comment by seabbs** [comment]
Thanks for the clarification!

My point was more that its effectively making a  one step ahead forecast and then indexing to a very non-intuitive date. In comparison, if you referenced it to date of infection for the new infections you would at least be able to index that against something (in that case your inferred cases by date of infection once 1 or 2 more generation of cases have happened). To do that I think you could approximate it by convolving the generation time and your current nowcast. To then get cases reported you would obviously need to further convolve by report delays and the incubation period. 

It is obviously totally fine to use this as a comparative measure but a little odd to label it as a Nowcast as that term is already widely understood as I defined in my previous comment. In many ways this is a one generation time ahead forecast but referenced to infectee infection date vs the traditional infection (or even more traditional report) date. 

Of course I could be barking up the wrong tree here. Do you have some references discussing this approach or other examples of it being used? It completely threw me and it was not at all clear how to interpret it. I can imagine it fairly easily being misinterpreted by others as well.

**Comment by MichelleKendall** [comment]
I'm sorry you find the date non-intuitive and the title misleading. The rationale for plotting the dates as we do is for more readily seeing the impacts of interventions. It's a really simplistic measure but it's helpful for its intended purpose. We introduced it in our Lancet Digital Health paper. I think it's fair to describe it as a nowcast; I see the term used broadly across many disciplines and contexts, e.g. https://en.wikipedia.org/wiki/Nowcasting 

I'm going to look in more detail early next week at the issues you've raised regarding the backcalculation and generation time; I think it will only be productive to revisit other queries after those more major concerns are addressed.
